name: 'Mis Fotografías de Panamá-Bocas del Toro y Kuna Yala '
favicon: null
layout_spectrum: 0.34552
typography_spectrum: 0.43436196097172797
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9b9c8a'
    - '#82816d'
    - '#b2b5a4'
    - '#775b50'
    - '#ffffff'
  brandStrength: 0.5625
  lightness: 0.875
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
